### PR TITLE
feat: improved reward system

### PR DESCRIPTION
**Pull request by grantdfoster**
**Description**

Problem Statement
Currently, our Bittensor subnet's reward system for Twitter data scraping is based solely on whether the provided data is valid or not. This binary approach doesn't incentivize miners to continuously improve the quantity and quality of data they provide. As a result, we may be missing opportunities to gather more valuable data and encourage healthy competition among miners.

Proposed Solution
Implement a more sophisticated reward mechanism that takes into account multiple factors:

Quantity of valid tweets (we should not verify every tweet)
Quality of tweets (this needs thought)
Continuous improvement over time
A kurtosis-based distribution to reward top performers while maintaining broader participation

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by teslashibe** [comment]
@grantdfoster added this: 

## Refined Initial Solution: v0.8.0 release

Implement a more sophisticated reward mechanism that takes into account multiple factors that rewards higher performing miners:

1. **Quantity** of valid tweets as defined by the count returned in a request for the GET Tweets/Posts endpoint.
2. A validator requests continuous data from miners as a synthetic request job from a centralized queue for now
3. Organic requests can still be sent to the network through a validator 
4. Round robin miner selection, if a miner returns 429 or no workers eligible, skip to the next miner. Issue here is latency will increase. We will worry about latency later. Set a parameter or constant that we can change for the number of miners selected in the round robin before return, "no miners available to fulfill the request"
5. Use a static representative JSON comparison using the LLM i.e. comparison `>0.50 `
6. A kurtosis-based distribution to reward top performers while maintaining broader participation
7. Generate an Jupyter model showing the curves for the new Kurtosis curve

## Next iteration: future release 

1. Think about how similarity check can be compared to a source of truth for 'quality' 
2. Quality of tweets (this needs thought)
3. Continuous improvement over time

# How can miners self-optimize for higher rewards
Miners can work independently to setup private clusters/networks using the Masa Protocol that is configured as its own private network with its their own set of Twitter Scraper Nodes. This allows miners to optimize and grow their capacity on the network which benefits the subnet by rewarding miners that bring the greatest capacity to the network. This capacity is harnessed by validators to scrape static data sets that are ranked by download volume in HF as well as organic requests that are submitted to validator API endpoints by developers who want real time data access. 

Screenshot 2024-08-28 at 11 30 51 AM

**Comment by teslashibe** [comment]
@grantdfoster implementation ticket to track this here: https://github.com/masa-finance/masa-bittensor/pull/227

**Comment by grantdfoster** [comment]
## Description
This PR implements a new reward system, and in doing so, refactors the codebase to favor the use of synapse's over a single forward function w/ request types.

Screenshot 2024-09-03 at 2 23 11 PM

## Features
The following features have been added:

- (version) - bumps internal versioning to 0.8.0
- (validator) - clean up endpoints / api
- (validator) - no need to run the protocol node as a validator anymore
- (validator) - support simultaneous synthetic and organic requests
- (validator) - create parallel threads running on loop for automatic behavior (syncing w/ metagraph, pinging miners for status, volume testing miners, scoring miners), all with their own dedicated cadence
- (validator) - score miners on kurtosis curve based on valid tweet volume
- (validator) - valid tweet determined as an embedded similarity score above 70%
- (validator) - index valid tweets and expose endpoint to fetch
- (miner) - simplify all requests into dedicated synapses with shared blacklist and priority functions
- (miner) - refactor requests and formatting of responses to be extremely minimal / scalable

**Comment by teslashibe** [comment]
@grantdfoster qq here. What would be a scoring outcome if a miner returns a one or both of the following errors:

case 1: `Twitter API rate limit exceeded (429 error)`

case 2: `there was an error authenticating with your Twitter credentials`


**case 1** occurs when the TW API rate limits

**case 2** occurs when a miner has a worker that is failing authentication 

My assumption here is that they would fail the similarity check. Can you help outline a couple of scenarios here and what the impact to scoring would be?

**Comment by grantdfoster** [comment]
@teslashibe yes correct - if there is no tweet, they get no recorded volume, which will get scored poorly over time.  As mentioned it's possible that we request 3 tweets but only get 2 back, in which case volume is 2.  A tweet is considered valid if it passes a certain similarity score, in this case based on an empty tweet embed

**Review by teslashibe — APPROVED** [review]
Lets go

**Pull request merged**
